import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class Insert_factory extends javax.swing.JFrame {
    
    String name = new String();
    int p_id;
    float profit;
    String choice;
    char ch,ch1;
    String categ = new String();
    String waste = new String();
    int mass;
    float toxicity;
    String recycle;
    char re;
    int fid;
    
    
    /**
     * Creates new form Insert_factory
     */
    public Insert_factory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purple_panel = new javax.swing.JPanel();
        profit_panel = new javax.swing.JPanel();
        profit_text = new javax.swing.JTextField();
        profit_label = new javax.swing.JLabel();
        percentage_text2 = new javax.swing.JTextField();
        category_panel = new javax.swing.JPanel();
        category_label = new javax.swing.JLabel();
        category_list = new java.awt.Choice();
        p_id_panel = new javax.swing.JPanel();
        p_id_label = new javax.swing.JLabel();
        p_id_text = new javax.swing.JTextField();
        factoryname_panel = new javax.swing.JPanel();
        factoryname_text = new javax.swing.JTextField();
        factoryname_label = new javax.swing.JLabel();
        insert_panel = new javax.swing.JPanel();
        insert_button = new javax.swing.JButton();
        license_panel = new javax.swing.JPanel();
        license_label1 = new javax.swing.JLabel();
        licensed_list = new java.awt.Choice();
        choose_label = new javax.swing.JLabel();
        wastename_panel = new javax.swing.JPanel();
        wastename_text = new javax.swing.JTextField();
        wastename_label = new javax.swing.JLabel();
        toxicity_panel = new javax.swing.JPanel();
        toxicity_text = new javax.swing.JTextField();
        toxicity_label = new javax.swing.JLabel();
        percentage_text = new javax.swing.JTextField();
        mass_panel7 = new javax.swing.JPanel();
        mass_text = new javax.swing.JTextField();
        mass_label = new javax.swing.JLabel();
        percentage_text1 = new javax.swing.JTextField();
        recycle_panel = new javax.swing.JPanel();
        recycle_label = new javax.swing.JLabel();
        recycle_list = new java.awt.Choice();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Factory insertion (Owner)");

        purple_panel.setBackground(new java.awt.Color(102, 0, 102));

        profit_panel.setBackground(new java.awt.Color(255, 255, 255));

        profit_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        profit_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        profit_text.setBorder(null);

        profit_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        profit_label.setText("Annual Profit:");

        percentage_text2.setEditable(false);
        percentage_text2.setBackground(new java.awt.Color(255, 255, 255));
        percentage_text2.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        percentage_text2.setForeground(new java.awt.Color(153, 153, 153));
        percentage_text2.setText("000 rupees");
        percentage_text2.setBorder(null);
        percentage_text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentage_text2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profit_panelLayout = new javax.swing.GroupLayout(profit_panel);
        profit_panel.setLayout(profit_panelLayout);
        profit_panelLayout.setHorizontalGroup(
            profit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profit_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profit_label, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profit_text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(percentage_text2)
                .addContainerGap())
        );
        profit_panelLayout.setVerticalGroup(
            profit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(profit_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(profit_label))
            .addComponent(percentage_text2)
        );

        category_panel.setBackground(new java.awt.Color(255, 255, 255));

        category_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        category_label.setText("Category:");

        category_list.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        category_list.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        category_list.removeAll();
        category_list.addItem("Choose one:");
        category_list.addItem("Small scale");
        category_list.addItem("Large scale");
        category_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                category_listItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout category_panelLayout = new javax.swing.GroupLayout(category_panel);
        category_panel.setLayout(category_panelLayout);
        category_panelLayout.setHorizontalGroup(
            category_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(category_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(category_label)
                .addGap(19, 19, 19)
                .addComponent(category_list, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        category_panelLayout.setVerticalGroup(
            category_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(category_panelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(category_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(category_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_id_panel.setBackground(new java.awt.Color(255, 255, 255));

        p_id_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        p_id_label.setText("Product ID:");

        p_id_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        p_id_text.setBorder(null);
        p_id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_id_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_id_panelLayout = new javax.swing.GroupLayout(p_id_panel);
        p_id_panel.setLayout(p_id_panelLayout);
        p_id_panelLayout.setHorizontalGroup(
            p_id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_id_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(p_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        p_id_panelLayout.setVerticalGroup(
            p_id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p_id_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(p_id_label))
        );

        factoryname_panel.setBackground(new java.awt.Color(255, 255, 255));

        factoryname_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        factoryname_text.setBorder(null);
        factoryname_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryname_textActionPerformed(evt);
            }
        });

        factoryname_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        factoryname_label.setText("Factory Name:");

        javax.swing.GroupLayout factoryname_panelLayout = new javax.swing.GroupLayout(factoryname_panel);
        factoryname_panel.setLayout(factoryname_panelLayout);
        factoryname_panelLayout.setHorizontalGroup(
            factoryname_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factoryname_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(factoryname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(factoryname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        factoryname_panelLayout.setVerticalGroup(
            factoryname_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factoryname_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(factoryname_text, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addComponent(factoryname_label))
        );

        insert_panel.setBackground(new java.awt.Color(0, 0, 0));

        insert_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        insert_button.setForeground(new java.awt.Color(255, 255, 255));
        insert_button.setText("Insert");
        insert_button.setContentAreaFilled(false);
        insert_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insert_panelLayout = new javax.swing.GroupLayout(insert_panel);
        insert_panel.setLayout(insert_panelLayout);
        insert_panelLayout.setHorizontalGroup(
            insert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insert_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        insert_panelLayout.setVerticalGroup(
            insert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insert_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        license_panel.setBackground(new java.awt.Color(255, 255, 255));

        license_label1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        license_label1.setText("Licensed:");

        licensed_list.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        licensed_list.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        licensed_list.removeAll();
        licensed_list.addItem("Choose one:");
        licensed_list.addItem("Yes");
        licensed_list.addItem("No");
        licensed_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                licensed_listItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout license_panelLayout = new javax.swing.GroupLayout(license_panel);
        license_panel.setLayout(license_panelLayout);
        license_panelLayout.setHorizontalGroup(
            license_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(license_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(license_label1)
                .addGap(23, 23, 23)
                .addComponent(licensed_list, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        license_panelLayout.setVerticalGroup(
            license_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(license_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(license_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(licensed_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(license_label1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        choose_label.setBackground(new java.awt.Color(102, 0, 102));
        choose_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        choose_label.setForeground(new java.awt.Color(255, 255, 255));
        choose_label.setText("Enter waste details:");

        wastename_panel.setBackground(new java.awt.Color(255, 255, 255));

        wastename_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        wastename_text.setBorder(null);

        wastename_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        wastename_label.setText("Waste name:");

        javax.swing.GroupLayout wastename_panelLayout = new javax.swing.GroupLayout(wastename_panel);
        wastename_panel.setLayout(wastename_panelLayout);
        wastename_panelLayout.setHorizontalGroup(
            wastename_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wastename_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wastename_label, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wastename_text, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        wastename_panelLayout.setVerticalGroup(
            wastename_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wastename_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(wastename_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(wastename_label))
        );

        toxicity_panel.setBackground(new java.awt.Color(255, 255, 255));

        toxicity_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        toxicity_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        toxicity_text.setBorder(null);

        toxicity_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        toxicity_label.setText("Toxicity:");

        percentage_text.setEditable(false);
        percentage_text.setBackground(new java.awt.Color(255, 255, 255));
        percentage_text.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        percentage_text.setForeground(new java.awt.Color(153, 153, 153));
        percentage_text.setText("%");
        percentage_text.setBorder(null);
        percentage_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentage_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toxicity_panelLayout = new javax.swing.GroupLayout(toxicity_panel);
        toxicity_panel.setLayout(toxicity_panelLayout);
        toxicity_panelLayout.setHorizontalGroup(
            toxicity_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toxicity_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toxicity_label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toxicity_text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(percentage_text, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        toxicity_panelLayout.setVerticalGroup(
            toxicity_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toxicity_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(toxicity_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(toxicity_label)
                .addComponent(percentage_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        mass_panel7.setBackground(new java.awt.Color(255, 255, 255));

        mass_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        mass_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        mass_text.setBorder(null);

        mass_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        mass_label.setText("Mass:");

        percentage_text1.setEditable(false);
        percentage_text1.setBackground(new java.awt.Color(255, 255, 255));
        percentage_text1.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        percentage_text1.setForeground(new java.awt.Color(153, 153, 153));
        percentage_text1.setText("tonnes per month");
        percentage_text1.setBorder(null);
        percentage_text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentage_text1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mass_panel7Layout = new javax.swing.GroupLayout(mass_panel7);
        mass_panel7.setLayout(mass_panel7Layout);
        mass_panel7Layout.setHorizontalGroup(
            mass_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mass_panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mass_text, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(percentage_text1))
        );
        mass_panel7Layout.setVerticalGroup(
            mass_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mass_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(mass_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(mass_label)
                .addComponent(percentage_text1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        recycle_panel.setBackground(new java.awt.Color(255, 255, 255));

        recycle_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        recycle_label.setText("Recyclable:");

        recycle_list.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        recycle_list.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        recycle_list.removeAll();
        recycle_list.addItem("Choose one:");
        recycle_list.addItem("Yes");
        recycle_list.addItem("No");
        recycle_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                recycle_listItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout recycle_panelLayout = new javax.swing.GroupLayout(recycle_panel);
        recycle_panel.setLayout(recycle_panelLayout);
        recycle_panelLayout.setHorizontalGroup(
            recycle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recycle_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recycle_label)
                .addGap(23, 23, 23)
                .addComponent(recycle_list, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        recycle_panelLayout.setVerticalGroup(
            recycle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recycle_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recycle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recycle_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recycle_label))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout purple_panelLayout = new javax.swing.GroupLayout(purple_panel);
        purple_panel.setLayout(purple_panelLayout);
        purple_panelLayout.setHorizontalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insert_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purple_panelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(profit_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_id_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(factoryname_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(category_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(license_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wastename_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toxicity_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mass_panel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recycle_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
            .addGroup(purple_panelLayout.createSequentialGroup()
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purple_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(choose_label))
                    .addGroup(purple_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        purple_panelLayout.setVerticalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purple_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(factoryname_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_id_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(category_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(license_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(choose_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wastename_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toxicity_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mass_panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recycle_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(insert_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_id_textActionPerformed

    private void factoryname_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryname_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryname_textActionPerformed

    private void insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_buttonActionPerformed

        try{

            name = factoryname_text.getText();
            /*choice = licensed_list.getSelectedItem();
            if (choice.equals("Yes"))
                ch = 'Y';
            else ch = 'N';
            categ = category_list.getSelectedItem();*/
            profit = Float.parseFloat(profit_text.getText()) * 1000;
            p_id = Integer.parseInt(p_id_text.getText());
            waste = wastename_text.getText();
            mass = Integer.parseInt(mass_text.getText());
            toxicity = Float.parseFloat(toxicity_text.getText());
            
            
            

            
            Class.forName("java.sql.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "table");
            Statement st= conn.createStatement();
            Statement st1= conn.createStatement();
            Statement st2 = conn.createStatement();
            Statement st3 = conn.createStatement();
            String query2 = "select * from factory;";
            String query3 = "select * from waste where waste.f_id in (select f_id from factory where f_name = '" + factoryname_text.getText() + "');";
            ResultSet rs200 = st2.executeQuery(query2);
            ResultSet rs100 = st3.executeQuery(query3);
            int flag = 0;
            login.load();
            while (rs200.next())
            {
                String f_name_import = rs200.getString("f_name");
                if(f_name_import.equals(factoryname_text.getText()))
                {
                    flag = 1;
                    
                    while(rs100.next())
                    {
                        String wimp = rs100.getString("w_name");
                        if((wimp.equals(wastename_text.getText())))
                        {
                            throw new ArithmeticException();
                            
                        }
                        else
                        {
                            fid = rs200.getInt("f_id");
                            break;
                        }
                    }
                }
                
            }
            st3.close();
            rs200.close();
            rs100.close();
            
            if(flag == 0)
                {
            
            
            
                    String query= "insert into factory values(" + (login.f_id) + "," + p_id + ",'" + name + "'," + profit + ",'" + categ + "','" + ch + "')";
                    String query1 = "insert into waste values('" + waste + "'," + (login.f_id) + "," + mass + "," + toxicity + ",'" + re + "');";
                    st.executeUpdate(query);
                    st1.executeUpdate(query1);
                    st.close();
                    st1.close();
                    st2.close();
                    st3.close();
                    conn.close();
                    JOptionPane.showMessageDialog(this,"Inserted new factory");
                }
            else
            {
                    String query1 = "insert into waste values('" + waste + "'," + fid + "," + mass + "," + toxicity + ",'" + re + "');";
                    st1.executeUpdate(query1);
                    JOptionPane.showMessageDialog(this,"Inserted new waste from factory " + factoryname_text.getText());
            }
                //throw new ArithmeticException() ;
            }
            
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error in inserting.");
            e.printStackTrace();
        }

        // TODO add your handling code here:

    }//GEN-LAST:event_insert_buttonActionPerformed

    private void licensed_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_licensed_listItemStateChanged
     
        choice = licensed_list.getSelectedItem();
            if (choice.equals("Yes"))
                ch = 'y';
            else if(choice.equals("No")) 
                ch = 'n';
            else
                ch = ' ';
            
     


// TODO add your handling code here:
    }//GEN-LAST:event_licensed_listItemStateChanged

    private void category_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_category_listItemStateChanged
       
        categ = category_list.getSelectedItem();
        
            if (categ.equals("Choose one:"))
                categ = null;

// TODO add your handling code here:
    }//GEN-LAST:event_category_listItemStateChanged

    private void recycle_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_recycle_listItemStateChanged
        recycle = recycle_list.getSelectedItem();
        if(recycle.equals("Yes"))
            re = 'y';
        else if(recycle.equals("No"))
            re = 'n';
        else
            re
                    = ' ';
        
// TODO add your handling code here:
    }//GEN-LAST:event_recycle_listItemStateChanged

    private void percentage_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentage_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentage_textActionPerformed

    private void percentage_text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentage_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentage_text1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.dispose();
        new Owner_insert().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void percentage_text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentage_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentage_text2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_factory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_factory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_factory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_factory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_factory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel category_label;
    private java.awt.Choice category_list;
    private javax.swing.JPanel category_panel;
    private javax.swing.JLabel choose_label;
    private javax.swing.JLabel factoryname_label;
    private javax.swing.JPanel factoryname_panel;
    private javax.swing.JTextField factoryname_text;
    private javax.swing.JButton insert_button;
    private javax.swing.JPanel insert_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel license_label1;
    private javax.swing.JPanel license_panel;
    private java.awt.Choice licensed_list;
    private javax.swing.JLabel mass_label;
    private javax.swing.JPanel mass_panel7;
    private javax.swing.JTextField mass_text;
    private javax.swing.JLabel p_id_label;
    private javax.swing.JPanel p_id_panel;
    private javax.swing.JTextField p_id_text;
    private javax.swing.JTextField percentage_text;
    private javax.swing.JTextField percentage_text1;
    private javax.swing.JTextField percentage_text2;
    private javax.swing.JLabel profit_label;
    private javax.swing.JPanel profit_panel;
    private javax.swing.JTextField profit_text;
    private javax.swing.JPanel purple_panel;
    private javax.swing.JLabel recycle_label;
    private java.awt.Choice recycle_list;
    private javax.swing.JPanel recycle_panel;
    private javax.swing.JLabel toxicity_label;
    private javax.swing.JPanel toxicity_panel;
    private javax.swing.JTextField toxicity_text;
    private javax.swing.JLabel wastename_label;
    private javax.swing.JPanel wastename_panel;
    private javax.swing.JTextField wastename_text;
    // End of variables declaration//GEN-END:variables
}
