
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class Insert_man_product extends javax.swing.JFrame {
    
    
    
    String name = new String();
    float price;
    int units;
    String rawmat;
    
    
    /**
     * Creates new form Insert_man_product
     */
    public Insert_man_product() {
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purple_panel = new javax.swing.JPanel();
        unitsperday_panel = new javax.swing.JPanel();
        unitsperday_text = new javax.swing.JTextField();
        unitsperday_label = new javax.swing.JLabel();
        rawmaterial_panel = new javax.swing.JPanel();
        rawmaterial_text = new javax.swing.JTextField();
        rawmaterial_label = new javax.swing.JLabel();
        unitprice_panel = new javax.swing.JPanel();
        unitprice_label = new javax.swing.JLabel();
        unitprice_text = new javax.swing.JTextField();
        productname_panel = new javax.swing.JPanel();
        productname_text = new javax.swing.JTextField();
        productname_label = new javax.swing.JLabel();
        insert_panel = new javax.swing.JPanel();
        insert_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product insertion (Manager)");

        purple_panel.setBackground(new java.awt.Color(102, 0, 102));

        unitsperday_panel.setBackground(new java.awt.Color(255, 255, 255));

        unitsperday_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        unitsperday_text.setBorder(null);

        unitsperday_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        unitsperday_label.setText("Units Manufactured Per Day:");

        javax.swing.GroupLayout unitsperday_panelLayout = new javax.swing.GroupLayout(unitsperday_panel);
        unitsperday_panel.setLayout(unitsperday_panelLayout);
        unitsperday_panelLayout.setHorizontalGroup(
            unitsperday_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitsperday_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unitsperday_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(unitsperday_text, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        unitsperday_panelLayout.setVerticalGroup(
            unitsperday_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitsperday_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(unitsperday_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(unitsperday_label))
        );

        rawmaterial_panel.setBackground(new java.awt.Color(255, 255, 255));

        rawmaterial_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        rawmaterial_text.setBorder(null);

        rawmaterial_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        rawmaterial_label.setText("Raw Material:");

        javax.swing.GroupLayout rawmaterial_panelLayout = new javax.swing.GroupLayout(rawmaterial_panel);
        rawmaterial_panel.setLayout(rawmaterial_panelLayout);
        rawmaterial_panelLayout.setHorizontalGroup(
            rawmaterial_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rawmaterial_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rawmaterial_label)
                .addGap(18, 18, 18)
                .addComponent(rawmaterial_text, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rawmaterial_panelLayout.setVerticalGroup(
            rawmaterial_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rawmaterial_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rawmaterial_text, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addComponent(rawmaterial_label))
        );

        unitprice_panel.setBackground(new java.awt.Color(255, 255, 255));

        unitprice_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        unitprice_label.setText("Unit Price:");

        unitprice_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        unitprice_text.setBorder(null);
        unitprice_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitprice_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout unitprice_panelLayout = new javax.swing.GroupLayout(unitprice_panel);
        unitprice_panel.setLayout(unitprice_panelLayout);
        unitprice_panelLayout.setHorizontalGroup(
            unitprice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitprice_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unitprice_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(unitprice_text, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        unitprice_panelLayout.setVerticalGroup(
            unitprice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unitprice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(unitprice_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(unitprice_label))
        );

        productname_panel.setBackground(new java.awt.Color(255, 255, 255));

        productname_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        productname_text.setBorder(null);
        productname_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productname_textActionPerformed(evt);
            }
        });

        productname_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        productname_label.setText("Product Name:");

        javax.swing.GroupLayout productname_panelLayout = new javax.swing.GroupLayout(productname_panel);
        productname_panel.setLayout(productname_panelLayout);
        productname_panelLayout.setHorizontalGroup(
            productname_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productname_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productname_panelLayout.setVerticalGroup(
            productname_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productname_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(productname_text, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addComponent(productname_label))
        );

        insert_panel.setBackground(new java.awt.Color(0, 0, 0));

        insert_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        insert_button.setForeground(new java.awt.Color(255, 255, 255));
        insert_button.setText("Insert");
        insert_button.setContentAreaFilled(false);
        insert_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insert_panelLayout = new javax.swing.GroupLayout(insert_panel);
        insert_panel.setLayout(insert_panelLayout);
        insert_panelLayout.setHorizontalGroup(
            insert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insert_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );
        insert_panelLayout.setVerticalGroup(
            insert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insert_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout purple_panelLayout = new javax.swing.GroupLayout(purple_panel);
        purple_panel.setLayout(purple_panelLayout);
        purple_panelLayout.setHorizontalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insert_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(purple_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purple_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(unitsperday_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(unitprice_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productname_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rawmaterial_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        purple_panelLayout.setVerticalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purple_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productname_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitprice_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitsperday_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rawmaterial_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(insert_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productname_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productname_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productname_textActionPerformed

    private void unitprice_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitprice_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitprice_textActionPerformed

    private void insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_buttonActionPerformed
        
       
        try{
            
           
            name = productname_text.getText();
            price = Float.parseFloat(unitprice_text.getText());
            units = Integer.parseInt(unitsperday_text.getText());
            rawmat = rawmaterial_text.getText();
            
            login.load();
            Class.forName("java.sql.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "table");
            Statement st= conn.createStatement();
            System.out.println(login.p_id);
            String query= "insert into product values(" + (login.p_id) + ",'" + name + "'," + price + "," + units + ",'" + rawmat +  "')";
            st.executeUpdate(query);
            
            st.close();
            conn.close();
            JOptionPane.showMessageDialog(this, "Inserted new product " + name);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error in insertion");
            e.printStackTrace();
        }
        
        
        
        // TODO add your handling code here:
       

    }//GEN-LAST:event_insert_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(true)
        {
            this.dispose();
            new Manager_insert().setVisible(true);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_man_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_man_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_man_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_man_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_man_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insert_button;
    private javax.swing.JPanel insert_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel productname_label;
    private javax.swing.JPanel productname_panel;
    private javax.swing.JTextField productname_text;
    private javax.swing.JPanel purple_panel;
    private javax.swing.JLabel rawmaterial_label;
    private javax.swing.JPanel rawmaterial_panel;
    private javax.swing.JTextField rawmaterial_text;
    private javax.swing.JLabel unitprice_label;
    private javax.swing.JPanel unitprice_panel;
    private javax.swing.JTextField unitprice_text;
    private javax.swing.JLabel unitsperday_label;
    private javax.swing.JPanel unitsperday_panel;
    private javax.swing.JTextField unitsperday_text;
    // End of variables declaration//GEN-END:variables
}
