import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class login extends javax.swing.JFrame {
    String user = new String();
    public static String us1, us2;
    String pass = new String();
    char pass_char_arr[];
    public static int user_ID, f_id, s_id, p_id, c_id, fid, in, pid, uid;
    /**
     * Creates new form login
     */
    
   
    
    
    public static void load()
    {
         try{                //load the latest value of user_ID from employee table to user_ID variable
           
            
            Class.forName("java.sql.Driver");
            Connection conn =(Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "table");
            Statement st = conn.createStatement();
            Statement st1 = conn.createStatement();
            Statement st2 = conn.createStatement();
            Statement st3 = conn.createStatement();
            Statement st4 = conn.createStatement();
            
            
            
            String query = "Select user_id from login_employee order by user_id desc limit 1;";
            String query1 = "Select f_id from factory order by f_id desc limit 1;";
            String query2 = "Select s_id from supplier order by s_id desc limit 1;";
            String query3 = "Select p_id from product order by p_id desc limit 1;";
            String query4 = "Select c_id from customer order by c_id desc limit 1;";
            
                                                           
            ResultSet rs = st.executeQuery(query);                                                     //execute select query
            ResultSet rs1 = st1.executeQuery(query1);
            ResultSet rs2 = st2.executeQuery(query2);
            ResultSet rs3 = st3.executeQuery(query3);
            ResultSet rs4 = st4.executeQuery(query4);
            
           
            
            while(rs.next())                                                                         //going to each row
            {
                user_ID = rs.getInt("user_ID");  
               
            }
            while(rs1.next())
            {
               f_id = rs1.getInt("f_id");
            }
            while(rs2.next())
            {
               s_id = rs2.getInt("s_id");
            }
            while(rs3.next())
            {
                p_id = rs3.getInt("p_id");
                
               
            }
            while(rs4.next())
            {
                c_id = rs4.getInt("c_id");
            }
            user_ID++;
            f_id++;
            s_id++;
            p_id++;
            c_id++;
            rs.close();
            rs1.close();
            rs2.close();
            rs3.close();
            rs4.close();
            st.close();
            conn.close();
         }catch(Exception e){
//            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
    }
    
    public login() {
        
       
        
        initComponents();
        user_text.addMouseListener(new MouseAdapter(){
           
            public void mouseClicked(MouseEvent e){
                user_text.setText(null);
                user_text.setEditable(true);
            }
        });
        
        pass_text.addMouseListener(new MouseAdapter(){
           
            public void mouseClicked(MouseEvent e){
                pass_text.setText(null);
                pass_text.setEditable(true);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        login_button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        user_text = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pass_text = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login\n");

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        login_button.setBackground(new java.awt.Color(0, 0, 0));
        login_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("Login");
        login_button.setBorder(null);
        login_button.setBorderPainted(false);
        login_button.setContentAreaFilled(false);
        login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel2.setText("User ID:");

        user_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        user_text.setBorder(null);
        user_text.setName(""); // NOI18N
        user_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_text, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_text, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel3.setText("Password:");

        pass_text.setBorder(null);
        pass_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pass_text, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pass_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
      try
      {
          user = user_text.getText();
          
      
            pass_char_arr = new char[ pass_text.getPassword().length]; 
            pass_char_arr = pass_text.getPassword();
            pass = new String(pass_char_arr);
            String select_query = "Select * from login_manager;";
            String select_query1 = "Select * from login_employee;";
            Class.forName("java.sql.Driver");
            
            Connection conn2=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "table");
             
            Statement st = conn2.createStatement();
            ResultSet rs = st.executeQuery(select_query);
            int flag = 0;
            while(rs.next())                                                                         //going to each row
            {
                String user_import = rs.getString("username");
                String pass_import = rs.getString("pass");
                if(user.equals(user_import) && pass.equals(pass_import))
                {  
                    flag = 1;
                    /*go to logged in table*/
                    if(user.equals("Anything"))
                    {
                        this.dispose();                                                      //going to a new frame. right click on project name under projects tab, new->jframe form.
                        new Owner().setVisible(true);
                    }
                    else
                    {
                        us1 = new String(pass);
                        us2 = new String(pass);
                        in = us1.indexOf('%');
                        if(in>0)
                        {
                            us1 = us1.substring(0, in);
                            us2 = us2.substring(in+1,us2.length());
                            fid = Integer.parseInt(us1);
                            pid = Integer.parseInt(us2);
                        }
                        System.out.println(fid);
                        System.out.println(pid);
                                this.dispose();
                                new Manager().setVisible(true);
                    }
                    
                }
                
                    
            }
            if(flag == 0)
            {
                int usid = 0;
                try
                {
                usid = Integer.parseInt(user_text.getText());
                uid = usid;
                }
                catch(Exception e)
                {
                    jLabel1.setVisible(true);
                    //JOptionPane.showMessageDialog(this, "Wrong username or password");
                }
                pass_char_arr = new char[ pass_text.getPassword().length]; 
                pass_char_arr = pass_text.getPassword();
                pass = new String(pass_char_arr);
               
                ResultSet rs1 = st.executeQuery(select_query1);
                int flag1 = 0;
                while(rs1.next())                                                                         //going to each row
                {
                    int user_import1 = rs1.getInt("user_ID");
                    String pass_import1 = rs1.getString("pass");
                    if(usid == user_import1 && pass.equals(pass_import1))
                    {  
                        /*go to logged in table*/
                        
                        flag1 = 1;
                        this.dispose();
                        new Employee().setVisible(true);
                    }


                }
                
                if(flag1 == 0)
                {
                    jLabel1.setVisible(true);
                    //JOptionPane.showMessageDialog(this, "Wrong username or password");
                }
            }
            rs.close();
            st.close();
            conn2.close();
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(this, e);
          e.printStackTrace();
      }

// TODO add your handling code here:
    }//GEN-LAST:event_login_buttonActionPerformed

    private void user_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_textActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_user_textActionPerformed

    private void pass_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_textActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_pass_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField pass_text;
    private javax.swing.JTextField user_text;
    // End of variables declaration//GEN-END:variables
}
