import javax.swing.JOptionPane;      
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class Manager_insert extends javax.swing.JFrame {

    /**
     * Creates new form Manager_insert
     */
    public Manager_insert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manager_insert_buttongroup = new javax.swing.ButtonGroup();
        error_dialog = new javax.swing.JDialog();
        error_panel1 = new javax.swing.JPanel();
        nothing_selected1 = new javax.swing.JLabel();
        okay_panel2 = new javax.swing.JPanel();
        okay_button2 = new javax.swing.JButton();
        purple_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        employee_panel = new javax.swing.JPanel();
        Employee = new javax.swing.JRadioButton();
        customer_panel = new javax.swing.JPanel();
        Customer = new javax.swing.JRadioButton();
        product_panel = new javax.swing.JPanel();
        Product = new javax.swing.JRadioButton();
        supplier_panel = new javax.swing.JPanel();
        Supplier = new javax.swing.JRadioButton();
        choose_label = new javax.swing.JLabel();
        okay_panel = new javax.swing.JPanel();
        okay_button = new javax.swing.JButton();
        cancel_panel = new javax.swing.JPanel();
        cancel_button = new javax.swing.JButton();
        choose_label1 = new javax.swing.JLabel();
        makes_panel = new javax.swing.JPanel();
        makes = new javax.swing.JRadioButton();
        purchase_panel = new javax.swing.JPanel();
        purchase = new javax.swing.JRadioButton();
        sells_panel = new javax.swing.JPanel();
        sells = new javax.swing.JRadioButton();

        error_dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        error_dialog.setBackground(new java.awt.Color(102, 0, 102));

        error_panel1.setBackground(new java.awt.Color(102, 0, 102));

        nothing_selected1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        nothing_selected1.setForeground(new java.awt.Color(255, 255, 255));
        nothing_selected1.setText("Nothing selected");

        okay_panel2.setBackground(new java.awt.Color(0, 0, 0));

        okay_button2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        okay_button2.setForeground(new java.awt.Color(255, 255, 255));
        okay_button2.setText("Okay");
        okay_button2.setContentAreaFilled(false);
        okay_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okay_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout okay_panel2Layout = new javax.swing.GroupLayout(okay_panel2);
        okay_panel2.setLayout(okay_panel2Layout);
        okay_panel2Layout.setHorizontalGroup(
            okay_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okay_button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        okay_panel2Layout.setVerticalGroup(
            okay_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okay_button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout error_panel1Layout = new javax.swing.GroupLayout(error_panel1);
        error_panel1.setLayout(error_panel1Layout);
        error_panel1Layout.setHorizontalGroup(
            error_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(error_panel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(nothing_selected1)
                .addContainerGap(88, Short.MAX_VALUE))
            .addComponent(okay_panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        error_panel1Layout.setVerticalGroup(
            error_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(error_panel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(nothing_selected1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(okay_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout error_dialogLayout = new javax.swing.GroupLayout(error_dialog.getContentPane());
        error_dialog.getContentPane().setLayout(error_dialogLayout);
        error_dialogLayout.setHorizontalGroup(
            error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(error_dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(error_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        error_dialogLayout.setVerticalGroup(
            error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(error_dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(error_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager insert");

        purple_panel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        employee_panel.setBackground(new java.awt.Color(255, 255, 255));

        Employee.setBackground(new java.awt.Color(255, 255, 255));
        manager_insert_buttongroup.add(Employee);
        Employee.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        Employee.setText("Employee");
        Employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout employee_panelLayout = new javax.swing.GroupLayout(employee_panel);
        employee_panel.setLayout(employee_panelLayout);
        employee_panelLayout.setHorizontalGroup(
            employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Employee)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        employee_panelLayout.setVerticalGroup(
            employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Employee)
                .addContainerGap())
        );

        customer_panel.setBackground(new java.awt.Color(255, 255, 255));

        Customer.setBackground(new java.awt.Color(255, 255, 255));
        manager_insert_buttongroup.add(Customer);
        Customer.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        Customer.setText("Customer");
        Customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customer_panelLayout = new javax.swing.GroupLayout(customer_panel);
        customer_panel.setLayout(customer_panelLayout);
        customer_panelLayout.setHorizontalGroup(
            customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Customer)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        customer_panelLayout.setVerticalGroup(
            customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Customer)
                .addContainerGap())
        );

        product_panel.setBackground(new java.awt.Color(255, 255, 255));

        Product.setBackground(new java.awt.Color(255, 255, 255));
        manager_insert_buttongroup.add(Product);
        Product.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        Product.setText("Product");
        Product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product_panelLayout = new javax.swing.GroupLayout(product_panel);
        product_panel.setLayout(product_panelLayout);
        product_panelLayout.setHorizontalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Product)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        product_panelLayout.setVerticalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Product)
                .addContainerGap())
        );

        supplier_panel.setBackground(new java.awt.Color(255, 255, 255));

        Supplier.setBackground(new java.awt.Color(255, 255, 255));
        manager_insert_buttongroup.add(Supplier);
        Supplier.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        Supplier.setText("Supplier");
        Supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout supplier_panelLayout = new javax.swing.GroupLayout(supplier_panel);
        supplier_panel.setLayout(supplier_panelLayout);
        supplier_panelLayout.setHorizontalGroup(
            supplier_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplier_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Supplier)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        supplier_panelLayout.setVerticalGroup(
            supplier_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplier_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Supplier)
                .addContainerGap())
        );

        choose_label.setBackground(new java.awt.Color(102, 0, 102));
        choose_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        choose_label.setForeground(new java.awt.Color(255, 255, 255));
        choose_label.setText("Choose table to insert into:");

        okay_panel.setBackground(new java.awt.Color(0, 0, 0));

        okay_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        okay_button.setForeground(new java.awt.Color(255, 255, 255));
        okay_button.setText("Okay");
        okay_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        okay_button.setContentAreaFilled(false);
        okay_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout okay_panelLayout = new javax.swing.GroupLayout(okay_panel);
        okay_panel.setLayout(okay_panelLayout);
        okay_panelLayout.setHorizontalGroup(
            okay_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okay_panelLayout.createSequentialGroup()
                .addComponent(okay_button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        okay_panelLayout.setVerticalGroup(
            okay_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okay_button, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        cancel_panel.setBackground(new java.awt.Color(0, 0, 0));

        cancel_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cancel_button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_button.setText("Cancel");
        cancel_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        cancel_button.setContentAreaFilled(false);
        cancel_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_button.setName("Insert (Owner)"); // NOI18N
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cancel_panelLayout = new javax.swing.GroupLayout(cancel_panel);
        cancel_panel.setLayout(cancel_panelLayout);
        cancel_panelLayout.setHorizontalGroup(
            cancel_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        cancel_panelLayout.setVerticalGroup(
            cancel_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        choose_label1.setBackground(new java.awt.Color(102, 0, 102));
        choose_label1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        choose_label1.setForeground(new java.awt.Color(255, 255, 255));
        choose_label1.setText("Daily updates:");

        makes_panel.setBackground(new java.awt.Color(255, 255, 255));

        makes.setBackground(new java.awt.Color(255, 255, 255));
        manager_insert_buttongroup.add(makes);
        makes.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        makes.setText("Manufactured");
        makes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        makes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout makes_panelLayout = new javax.swing.GroupLayout(makes_panel);
        makes_panel.setLayout(makes_panelLayout);
        makes_panelLayout.setHorizontalGroup(
            makes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makes_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        makes_panelLayout.setVerticalGroup(
            makes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makes_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makes)
                .addContainerGap())
        );

        purchase_panel.setBackground(new java.awt.Color(255, 255, 255));

        purchase.setBackground(new java.awt.Color(255, 255, 255));
        manager_insert_buttongroup.add(purchase);
        purchase.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        purchase.setText("Purchased");
        purchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout purchase_panelLayout = new javax.swing.GroupLayout(purchase_panel);
        purchase_panel.setLayout(purchase_panelLayout);
        purchase_panelLayout.setHorizontalGroup(
            purchase_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchase_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(purchase)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        purchase_panelLayout.setVerticalGroup(
            purchase_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchase_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(purchase)
                .addContainerGap())
        );

        sells_panel.setBackground(new java.awt.Color(255, 255, 255));

        sells.setBackground(new java.awt.Color(255, 255, 255));
        manager_insert_buttongroup.add(sells);
        sells.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        sells.setText("Sold");
        sells.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sells.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sells_panelLayout = new javax.swing.GroupLayout(sells_panel);
        sells_panel.setLayout(sells_panelLayout);
        sells_panelLayout.setHorizontalGroup(
            sells_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sells_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sells)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        sells_panelLayout.setVerticalGroup(
            sells_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sells_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sells)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(okay_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancel_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(employee_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customer_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(supplier_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sells_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(purchase_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makes_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(choose_label)
                            .addGap(97, 97, 97)))
                    .addComponent(choose_label1)
                    .addComponent(product_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choose_label)
                .addGap(18, 18, 18)
                .addComponent(product_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplier_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customer_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(employee_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(choose_label1)
                .addGap(18, 18, 18)
                .addComponent(makes_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(purchase_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sells_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okay_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout purple_panelLayout = new javax.swing.GroupLayout(purple_panel);
        purple_panel.setLayout(purple_panelLayout);
        purple_panelLayout.setHorizontalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        purple_panelLayout.setVerticalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerActionPerformed

    private void ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductActionPerformed

    private void okay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_buttonActionPerformed

        if(Product.isSelected())
        {
            this.dispose();
            new Insert_man_product().setVisible(true);
        }
        else if(Supplier.isSelected())
        {
            this.dispose();
            new Insert_man_supplier().setVisible(true);
        }
        else if(Customer.isSelected())
        {
            this.dispose();
            new Insert_man_customer().setVisible(true);
        }
        else if(Employee.isSelected())
        {
            this.dispose();
            new Insert_man_employee().setVisible(true);
        }
        else if(makes.isSelected())
        {
            this.dispose();
            new Makes().setVisible(true);
        }
        else if(purchase.isSelected())
        {
            this.dispose();
            new Purchase().setVisible(true);
        }
        else if(sells.isSelected())
        {
            this.dispose();
            new Sells().setVisible(true);
        }
        

        else
        {
            JOptionPane.showMessageDialog(error_dialog,"Nothing entered");
            //error_panel.setVisible(true);
        }

        //new login().user_ID++;//THIS IS NOT SUPPOSED TO BE HERE. PUT THIS IN ANOTHER .JAVA FILE WHERE YOU'LL INSERT VALUES FOR EMPLOYEES.

        //System.out.println(login.user_ID);
        //System.out.println(login.f_id);
        //System.out.println(login.s_id);

        // TODO add your handling code here:
    }//GEN-LAST:event_okay_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed

        this.dispose();                                                      //going to a new frame. right click on project name under projects tab, new->jframe form.
        new Manager().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void okay_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okay_button2ActionPerformed

    private void makesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makesActionPerformed

    private void sellsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Customer;
    private javax.swing.JRadioButton Employee;
    private javax.swing.JRadioButton Product;
    private javax.swing.JRadioButton Supplier;
    private javax.swing.JButton cancel_button;
    private javax.swing.JPanel cancel_panel;
    private javax.swing.JLabel choose_label;
    private javax.swing.JLabel choose_label1;
    private javax.swing.JPanel customer_panel;
    private javax.swing.JPanel employee_panel;
    private javax.swing.JDialog error_dialog;
    private javax.swing.JPanel error_panel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton makes;
    private javax.swing.JPanel makes_panel;
    private javax.swing.ButtonGroup manager_insert_buttongroup;
    private javax.swing.JLabel nothing_selected1;
    private javax.swing.JButton okay_button;
    private javax.swing.JButton okay_button2;
    private javax.swing.JPanel okay_panel;
    private javax.swing.JPanel okay_panel2;
    private javax.swing.JPanel product_panel;
    private javax.swing.JRadioButton purchase;
    private javax.swing.JPanel purchase_panel;
    private javax.swing.JPanel purple_panel;
    private javax.swing.JRadioButton sells;
    private javax.swing.JPanel sells_panel;
    private javax.swing.JPanel supplier_panel;
    // End of variables declaration//GEN-END:variables
}
