
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class Owner extends javax.swing.JFrame {

    /**
     * Creates new form Owner
     */
    public Owner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purple_panel = new javax.swing.JPanel();
        insert_panel = new javax.swing.JPanel();
        insert_button = new javax.swing.JButton();
        black_panel_1 = new javax.swing.JPanel();
        modify_panel = new javax.swing.JPanel();
        modify_button = new javax.swing.JButton();
        black_panel_5 = new javax.swing.JPanel();
        delete_panel = new javax.swing.JPanel();
        delete_button = new javax.swing.JButton();
        black_panel_6 = new javax.swing.JPanel();
        view_panel = new javax.swing.JPanel();
        view_button = new javax.swing.JButton();
        black_panel_7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        black_panel_8 = new javax.swing.JPanel();
        view_panel1 = new javax.swing.JPanel();
        view_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Owner");

        purple_panel.setBackground(new java.awt.Color(102, 0, 102));

        insert_panel.setBackground(new java.awt.Color(255, 255, 255));

        insert_button.setBackground(new java.awt.Color(0, 0, 0));
        insert_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        insert_button.setText("Insert");
        insert_button.setBorderPainted(false);
        insert_button.setContentAreaFilled(false);
        insert_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        insert_button.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insert_panelLayout = new javax.swing.GroupLayout(insert_panel);
        insert_panel.setLayout(insert_panelLayout);
        insert_panelLayout.setHorizontalGroup(
            insert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insert_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        insert_panelLayout.setVerticalGroup(
            insert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insert_panelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(insert_button, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        black_panel_1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout black_panel_1Layout = new javax.swing.GroupLayout(black_panel_1);
        black_panel_1.setLayout(black_panel_1Layout);
        black_panel_1Layout.setHorizontalGroup(
            black_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        black_panel_1Layout.setVerticalGroup(
            black_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        modify_panel.setBackground(new java.awt.Color(255, 255, 255));

        modify_button.setBackground(new java.awt.Color(0, 0, 0));
        modify_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        modify_button.setText("Modify");
        modify_button.setBorderPainted(false);
        modify_button.setContentAreaFilled(false);
        modify_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modify_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        modify_button.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        modify_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modify_panelLayout = new javax.swing.GroupLayout(modify_panel);
        modify_panel.setLayout(modify_panelLayout);
        modify_panelLayout.setHorizontalGroup(
            modify_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modify_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modify_button, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modify_panelLayout.setVerticalGroup(
            modify_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modify_panelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(modify_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        black_panel_5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout black_panel_5Layout = new javax.swing.GroupLayout(black_panel_5);
        black_panel_5.setLayout(black_panel_5Layout);
        black_panel_5Layout.setHorizontalGroup(
            black_panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        black_panel_5Layout.setVerticalGroup(
            black_panel_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        delete_panel.setBackground(new java.awt.Color(255, 255, 255));

        delete_button.setBackground(new java.awt.Color(0, 0, 0));
        delete_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        delete_button.setText("Delete");
        delete_button.setBorderPainted(false);
        delete_button.setContentAreaFilled(false);
        delete_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        delete_button.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout delete_panelLayout = new javax.swing.GroupLayout(delete_panel);
        delete_panel.setLayout(delete_panelLayout);
        delete_panelLayout.setHorizontalGroup(
            delete_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        delete_panelLayout.setVerticalGroup(
            delete_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delete_panelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        black_panel_6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout black_panel_6Layout = new javax.swing.GroupLayout(black_panel_6);
        black_panel_6.setLayout(black_panel_6Layout);
        black_panel_6Layout.setHorizontalGroup(
            black_panel_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        black_panel_6Layout.setVerticalGroup(
            black_panel_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        view_panel.setBackground(new java.awt.Color(255, 255, 255));

        view_button.setBackground(new java.awt.Color(0, 0, 0));
        view_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        view_button.setText("View");
        view_button.setBorderPainted(false);
        view_button.setContentAreaFilled(false);
        view_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        view_button.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout view_panelLayout = new javax.swing.GroupLayout(view_panel);
        view_panel.setLayout(view_panelLayout);
        view_panelLayout.setHorizontalGroup(
            view_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view_button, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        view_panelLayout.setVerticalGroup(
            view_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_panelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(view_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        black_panel_7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout black_panel_7Layout = new javax.swing.GroupLayout(black_panel_7);
        black_panel_7.setLayout(black_panel_7Layout);
        black_panel_7Layout.setHorizontalGroup(
            black_panel_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        black_panel_7Layout.setVerticalGroup(
            black_panel_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        black_panel_8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout black_panel_8Layout = new javax.swing.GroupLayout(black_panel_8);
        black_panel_8.setLayout(black_panel_8Layout);
        black_panel_8Layout.setHorizontalGroup(
            black_panel_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        black_panel_8Layout.setVerticalGroup(
            black_panel_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        view_panel1.setBackground(new java.awt.Color(255, 255, 255));

        view_button1.setBackground(new java.awt.Color(0, 0, 0));
        view_button1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        view_button1.setText("Create notitfication");
        view_button1.setBorderPainted(false);
        view_button1.setContentAreaFilled(false);
        view_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_button1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        view_button1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        view_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout view_panel1Layout = new javax.swing.GroupLayout(view_panel1);
        view_panel1.setLayout(view_panel1Layout);
        view_panel1Layout.setHorizontalGroup(
            view_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        view_panel1Layout.setVerticalGroup(
            view_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_panel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(view_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout purple_panelLayout = new javax.swing.GroupLayout(purple_panel);
        purple_panel.setLayout(purple_panelLayout);
        purple_panelLayout.setHorizontalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purple_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(purple_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purple_panelLayout.createSequentialGroup()
                        .addComponent(black_panel_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(view_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(purple_panelLayout.createSequentialGroup()
                            .addComponent(black_panel_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(view_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(purple_panelLayout.createSequentialGroup()
                                .addComponent(black_panel_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(delete_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(purple_panelLayout.createSequentialGroup()
                                .addComponent(black_panel_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(modify_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(purple_panelLayout.createSequentialGroup()
                                .addComponent(black_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(insert_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        purple_panelLayout.setVerticalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purple_panelLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insert_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(black_panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modify_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(black_panel_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(black_panel_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(black_panel_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(black_panel_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_buttonActionPerformed
        this.dispose();                                                      //going to a new frame. right click on project name under projects tab, new->jframe form.
        new Owner_insert().setVisible(true);




        // TODO add your handling code here:
    }//GEN-LAST:event_insert_buttonActionPerformed

    private void modify_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_buttonActionPerformed
    
        this.dispose();                                                      //going to a new frame. right click on project name under projects tab, new->jframe form.
        new Owner_update().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_modify_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        
        this.dispose();                                                      //going to a new frame. right click on project name under projects tab, new->jframe form.
        new Owner_delete().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_buttonActionPerformed
        
        this.dispose();                                                      //going to a new frame. right click on project name under projects tab, new->jframe form.
        new Owner_view().setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_view_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this,"You have successfully logged out.");
        this.dispose();
        new login().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void view_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_button1ActionPerformed
        
        this.dispose();
        new Notify().setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_view_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel black_panel_1;
    private javax.swing.JPanel black_panel_5;
    private javax.swing.JPanel black_panel_6;
    private javax.swing.JPanel black_panel_7;
    private javax.swing.JPanel black_panel_8;
    private javax.swing.JButton delete_button;
    private javax.swing.JPanel delete_panel;
    private javax.swing.JButton insert_button;
    private javax.swing.JPanel insert_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton modify_button;
    private javax.swing.JPanel modify_panel;
    private javax.swing.JPanel purple_panel;
    private javax.swing.JButton view_button;
    private javax.swing.JButton view_button1;
    private javax.swing.JPanel view_panel;
    private javax.swing.JPanel view_panel1;
    // End of variables declaration//GEN-END:variables
}
