
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aksha_000
 */
public class Owner_update extends javax.swing.JFrame {

    /**
     * Creates new form Owner_update
     */
    public Owner_update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        factory_panel = new javax.swing.JPanel();
        Factory = new javax.swing.JRadioButton();
        employee_panel = new javax.swing.JPanel();
        Employee = new javax.swing.JRadioButton();
        customer_panel = new javax.swing.JPanel();
        Customer = new javax.swing.JRadioButton();
        product_panel = new javax.swing.JPanel();
        Product = new javax.swing.JRadioButton();
        supplier_panel = new javax.swing.JPanel();
        Supplier = new javax.swing.JRadioButton();
        choose_label = new javax.swing.JLabel();
        okay_panel = new javax.swing.JPanel();
        okay_button = new javax.swing.JButton();
        cancel_panel = new javax.swing.JPanel();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Updation (Owner)");

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        factory_panel.setBackground(new java.awt.Color(255, 255, 255));

        Factory.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Factory);
        Factory.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        Factory.setText("Factory");
        Factory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Factory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout factory_panelLayout = new javax.swing.GroupLayout(factory_panel);
        factory_panel.setLayout(factory_panelLayout);
        factory_panelLayout.setHorizontalGroup(
            factory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factory_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Factory)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        factory_panelLayout.setVerticalGroup(
            factory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factory_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Factory)
                .addContainerGap())
        );

        employee_panel.setBackground(new java.awt.Color(255, 255, 255));

        Employee.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Employee);
        Employee.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        Employee.setText("Employee");
        Employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout employee_panelLayout = new javax.swing.GroupLayout(employee_panel);
        employee_panel.setLayout(employee_panelLayout);
        employee_panelLayout.setHorizontalGroup(
            employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Employee)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        employee_panelLayout.setVerticalGroup(
            employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Employee)
                .addContainerGap())
        );

        customer_panel.setBackground(new java.awt.Color(255, 255, 255));

        Customer.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Customer);
        Customer.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        Customer.setText("Customer");
        Customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customer_panelLayout = new javax.swing.GroupLayout(customer_panel);
        customer_panel.setLayout(customer_panelLayout);
        customer_panelLayout.setHorizontalGroup(
            customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Customer)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        customer_panelLayout.setVerticalGroup(
            customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Customer)
                .addContainerGap())
        );

        product_panel.setBackground(new java.awt.Color(255, 255, 255));

        Product.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Product);
        Product.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        Product.setText("Product");
        Product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout product_panelLayout = new javax.swing.GroupLayout(product_panel);
        product_panel.setLayout(product_panelLayout);
        product_panelLayout.setHorizontalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Product)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        product_panelLayout.setVerticalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Product)
                .addContainerGap())
        );

        supplier_panel.setBackground(new java.awt.Color(255, 255, 255));

        Supplier.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Supplier);
        Supplier.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        Supplier.setText("Supplier");
        Supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout supplier_panelLayout = new javax.swing.GroupLayout(supplier_panel);
        supplier_panel.setLayout(supplier_panelLayout);
        supplier_panelLayout.setHorizontalGroup(
            supplier_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplier_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Supplier)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        supplier_panelLayout.setVerticalGroup(
            supplier_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplier_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Supplier)
                .addContainerGap())
        );

        choose_label.setBackground(new java.awt.Color(102, 0, 102));
        choose_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        choose_label.setForeground(new java.awt.Color(255, 255, 255));
        choose_label.setText("Choose table to update:");

        okay_panel.setBackground(new java.awt.Color(0, 0, 0));

        okay_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        okay_button.setForeground(new java.awt.Color(255, 255, 255));
        okay_button.setText("Okay");
        okay_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        okay_button.setContentAreaFilled(false);
        okay_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout okay_panelLayout = new javax.swing.GroupLayout(okay_panel);
        okay_panel.setLayout(okay_panelLayout);
        okay_panelLayout.setHorizontalGroup(
            okay_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okay_panelLayout.createSequentialGroup()
                .addComponent(okay_button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        okay_panelLayout.setVerticalGroup(
            okay_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okay_button, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        cancel_panel.setBackground(new java.awt.Color(0, 0, 0));

        cancel_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cancel_button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_button.setText("Cancel");
        cancel_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        cancel_button.setContentAreaFilled(false);
        cancel_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_button.setName("Insert (Owner)"); // NOI18N
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cancel_panelLayout = new javax.swing.GroupLayout(cancel_panel);
        cancel_panel.setLayout(cancel_panelLayout);
        cancel_panelLayout.setHorizontalGroup(
            cancel_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancel_panelLayout.createSequentialGroup()
                .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cancel_panelLayout.setVerticalGroup(
            cancel_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancel_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(okay_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cancel_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employee_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(customer_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(supplier_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(factory_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(product_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(choose_label))))))))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choose_label)
                .addGap(18, 18, 18)
                .addComponent(product_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(factory_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(supplier_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customer_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(employee_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okay_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FactoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FactoryActionPerformed

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerActionPerformed

    private void ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductActionPerformed

    private void okay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_buttonActionPerformed

        if(Product.isSelected())
        {
            this.dispose();
            new Update_product().setVisible(true);
        }
        else if(Factory.isSelected())
        {
            this.dispose();
            new Update_factory().setVisible(true);
        }
        else if(Supplier.isSelected())
        {
            this.dispose();
            new Update_supplier().setVisible(true);
        }
        else if(Customer.isSelected())
        {
            this.dispose();
            new Update_customer().setVisible(true);
        }
        else if(Employee.isSelected())
        {
            this.dispose();
            new Update_employee().setVisible(true);
        }

        else
        {
            JOptionPane.showMessageDialog(this,"Nothing entered");
            //error_panel.setVisible(true);
        }

        //new login().user_ID++;//THIS IS NOT SUPPOSED TO BE HERE. PUT THIS IN ANOTHER .JAVA FILE WHERE YOU'LL INSERT VALUES FOR EMPLOYEES.

        //System.out.println(login.user_ID);
        //System.out.println(login.f_id);
        //System.out.println(login.s_id);

        // TODO add your handling code here:
    }//GEN-LAST:event_okay_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed

        this.dispose();                                                      //going to a new frame. right click on project name under projects tab, new->jframe form.
        new Owner().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Customer;
    private javax.swing.JRadioButton Employee;
    private javax.swing.JRadioButton Factory;
    private javax.swing.JRadioButton Product;
    private javax.swing.JRadioButton Supplier;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel_button;
    private javax.swing.JPanel cancel_panel;
    private javax.swing.JLabel choose_label;
    private javax.swing.JPanel customer_panel;
    private javax.swing.JPanel employee_panel;
    private javax.swing.JPanel factory_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton okay_button;
    private javax.swing.JPanel okay_panel;
    private javax.swing.JPanel product_panel;
    private javax.swing.JPanel supplier_panel;
    // End of variables declaration//GEN-END:variables
}
