import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class Update_employee extends javax.swing.JFrame {

    String name = new String();
    int f_id, p_id;
    String ph = new String();
    String email = new String();
    String addr = new String();
    String post = new String();
    float sal;
    String date = new String();
    String bdate = new String();    
    /**
     * Creates new form Update_employee
     */
    public Update_employee() {
        initComponents();
      
        date_text.addMouseListener(new MouseAdapter(){
           
            public void mouseClicked(MouseEvent e){
                date_text.setText(null);
                date_text.setEditable(true);
            }
        });
        bdate_text.addMouseListener(new MouseAdapter(){
           
            public void mouseClicked(MouseEvent e){
                bdate_text.setText(null);
                bdate_text.setEditable(true);
            }
        });
        
        if(!f_id_text.getText().isEmpty())
        {
            try{
                Class.forName("java.sql.Driver");
            
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "table");
                Statement st= conn.createStatement();
                int f = Integer.parseInt(f_id_text.getText());
                String query4 = "select f_id, p_id from makes where f_id = " + f + ";";
                ResultSet rs = st.executeQuery(query4);
                while(rs.next())
                {
                    int fimp = rs.getInt("f_id");
                    if(fimp == f)
                    p_id_text.setText(Integer.toString(rs.getInt("p_id")));
                }
            }
            catch(Exception e)
            {
                
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purple_panel = new javax.swing.JPanel();
        phone_panel = new javax.swing.JPanel();
        phone_text = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        p_id_panel = new javax.swing.JPanel();
        p_id_label = new javax.swing.JLabel();
        p_id_text = new javax.swing.JTextField();
        name_panel = new javax.swing.JPanel();
        name_text = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        insert_panel = new javax.swing.JPanel();
        update_button = new javax.swing.JButton();
        addr_panel = new javax.swing.JPanel();
        addr_text = new javax.swing.JTextField();
        addr_label = new javax.swing.JLabel();
        f_id_panel = new javax.swing.JPanel();
        f_id_label = new javax.swing.JLabel();
        f_id_text = new javax.swing.JTextField();
        f_id_text1 = new javax.swing.JTextField();
        date_panel = new javax.swing.JPanel();
        date_label = new javax.swing.JLabel();
        date_text = new javax.swing.JTextField();
        today = new javax.swing.JCheckBox();
        salary_panel = new javax.swing.JPanel();
        sal_text = new javax.swing.JTextField();
        sal_label = new javax.swing.JLabel();
        pa_text = new javax.swing.JTextField();
        bdate_panel = new javax.swing.JPanel();
        bdate_label = new javax.swing.JLabel();
        bdate_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        e_id_text = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        post_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee insertion (Owner)");

        purple_panel.setBackground(new java.awt.Color(102, 0, 102));
        purple_panel.setPreferredSize(new java.awt.Dimension(428, 570));

        phone_panel.setBackground(new java.awt.Color(255, 255, 255));

        phone_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        phone_text.setBorder(null);
        phone_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_textActionPerformed(evt);
            }
        });

        phone_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        phone_label.setText("Phone:");

        javax.swing.GroupLayout phone_panelLayout = new javax.swing.GroupLayout(phone_panel);
        phone_panel.setLayout(phone_panelLayout);
        phone_panelLayout.setHorizontalGroup(
            phone_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phone_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(phone_text, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        phone_panelLayout.setVerticalGroup(
            phone_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phone_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(phone_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(phone_label))
        );

        p_id_panel.setBackground(new java.awt.Color(255, 255, 255));

        p_id_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        p_id_label.setText("Product ID:");

        p_id_text.setEditable(false);
        p_id_text.setBackground(new java.awt.Color(255, 255, 255));
        p_id_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        p_id_text.setBorder(null);
        p_id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_id_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_id_panelLayout = new javax.swing.GroupLayout(p_id_panel);
        p_id_panel.setLayout(p_id_panelLayout);
        p_id_panelLayout.setHorizontalGroup(
            p_id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_id_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_id_text)
                .addGap(3, 3, 3))
        );
        p_id_panelLayout.setVerticalGroup(
            p_id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(p_id_text)
                .addComponent(p_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        name_panel.setBackground(new java.awt.Color(255, 255, 255));

        name_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        name_text.setBorder(null);
        name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textActionPerformed(evt);
            }
        });

        name_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        name_label.setText("Employee name:");

        javax.swing.GroupLayout name_panelLayout = new javax.swing.GroupLayout(name_panel);
        name_panel.setLayout(name_panelLayout);
        name_panelLayout.setHorizontalGroup(
            name_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_text))
        );
        name_panelLayout.setVerticalGroup(
            name_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(name_text)
                .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        insert_panel.setBackground(new java.awt.Color(0, 0, 0));

        update_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        update_button.setForeground(new java.awt.Color(255, 255, 255));
        update_button.setText("Update");
        update_button.setContentAreaFilled(false);
        update_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insert_panelLayout = new javax.swing.GroupLayout(insert_panel);
        insert_panel.setLayout(insert_panelLayout);
        insert_panelLayout.setHorizontalGroup(
            insert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(update_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        insert_panelLayout.setVerticalGroup(
            insert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insert_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        addr_panel.setBackground(new java.awt.Color(255, 255, 255));

        addr_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        addr_text.setBorder(null);

        addr_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        addr_label.setText("Address:");

        javax.swing.GroupLayout addr_panelLayout = new javax.swing.GroupLayout(addr_panel);
        addr_panel.setLayout(addr_panelLayout);
        addr_panelLayout.setHorizontalGroup(
            addr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addr_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addr_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addr_text)
                .addGap(8, 8, 8))
        );
        addr_panelLayout.setVerticalGroup(
            addr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(addr_text)
                .addComponent(addr_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        f_id_panel.setBackground(new java.awt.Color(255, 255, 255));

        f_id_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        f_id_label.setText("Factory ID:");

        f_id_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        f_id_text.setBorder(null);
        f_id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_id_textActionPerformed(evt);
            }
        });

        f_id_text1.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        f_id_text1.setForeground(new java.awt.Color(153, 153, 153));
        f_id_text1.setText("Please press enter");
        f_id_text1.setBorder(null);
        f_id_text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_id_text1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout f_id_panelLayout = new javax.swing.GroupLayout(f_id_panel);
        f_id_panel.setLayout(f_id_panelLayout);
        f_id_panelLayout.setHorizontalGroup(
            f_id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_id_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(f_id_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        f_id_panelLayout.setVerticalGroup(
            f_id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f_id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(f_id_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(f_id_label)
                .addComponent(f_id_text1))
        );

        date_panel.setBackground(new java.awt.Color(255, 255, 255));

        date_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        date_label.setText("Join Date:");

        date_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        date_text.setText("YYYY-MM-DD");
        date_text.setBorder(null);

        today.setBackground(new java.awt.Color(255, 255, 255));
        today.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        today.setText("Today");
        today.setBorder(null);
        today.setContentAreaFilled(false);
        today.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        today.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout date_panelLayout = new javax.swing.GroupLayout(date_panel);
        date_panel.setLayout(date_panelLayout);
        date_panelLayout.setHorizontalGroup(
            date_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(date_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(today)
                .addGap(63, 63, 63))
            .addGroup(date_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, date_panelLayout.createSequentialGroup()
                    .addContainerGap(84, Short.MAX_VALUE)
                    .addComponent(date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(156, 156, 156)))
        );
        date_panelLayout.setVerticalGroup(
            date_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(date_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(today, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(date_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(date_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        salary_panel.setBackground(new java.awt.Color(255, 255, 255));

        sal_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        sal_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        sal_text.setBorder(null);
        sal_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sal_textActionPerformed(evt);
            }
        });

        sal_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        sal_label.setText("Salary:");

        pa_text.setEditable(false);
        pa_text.setBackground(new java.awt.Color(255, 255, 255));
        pa_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        pa_text.setForeground(new java.awt.Color(153, 153, 153));
        pa_text.setText("000 per annum");
        pa_text.setBorder(null);
        pa_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pa_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout salary_panelLayout = new javax.swing.GroupLayout(salary_panel);
        salary_panel.setLayout(salary_panelLayout);
        salary_panelLayout.setHorizontalGroup(
            salary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salary_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sal_label, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sal_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pa_text, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        salary_panelLayout.setVerticalGroup(
            salary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salary_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sal_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(sal_label)
                .addComponent(pa_text))
        );

        bdate_panel.setBackground(new java.awt.Color(255, 255, 255));

        bdate_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        bdate_label.setText("Birthday:");

        bdate_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        bdate_text.setText("YYYY-MM-DD");
        bdate_text.setBorder(null);

        javax.swing.GroupLayout bdate_panelLayout = new javax.swing.GroupLayout(bdate_panel);
        bdate_panel.setLayout(bdate_panelLayout);
        bdate_panelLayout.setHorizontalGroup(
            bdate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bdate_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bdate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(bdate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bdate_panelLayout.createSequentialGroup()
                    .addGap(0, 84, Short.MAX_VALUE)
                    .addComponent(bdate_text, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        bdate_panelLayout.setVerticalGroup(
            bdate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bdate_label, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addGroup(bdate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bdate_text, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel1.setText("Employee ID:");

        e_id_text.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        e_id_text.setBorder(null);
        e_id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_id_textActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Go");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(e_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(e_id_text)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel2.setText("Post:");

        post_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        post_text.setBorder(null);
        post_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                post_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(post_text, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(post_text)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout purple_panelLayout = new javax.swing.GroupLayout(purple_panel);
        purple_panel.setLayout(purple_panelLayout);
        purple_panelLayout.setHorizontalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insert_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(purple_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purple_panelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addr_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phone_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_id_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f_id_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salary_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdate_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        purple_panelLayout.setVerticalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purple_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addr_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_id_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_id_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salary_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdate_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insert_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phone_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_textActionPerformed

    private void p_id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_id_textActionPerformed

    private void name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed

        try{
            login.load();

            name = name_text.getText();
            post=post_text.getText();
            p_id = Integer.parseInt(p_id_text.getText());
            f_id = Integer.parseInt(f_id_text.getText());
            String in1, in2;
            int ind;
            in1 = name.substring(0, 1);
            System.out.println(in1);
            ind = name.indexOf(" ");
            if(ind>0)
                in2 = name.substring(ind+1, ind+2);
            else
                in2 = "_";
            System.out.println(in2);
            email = in1 + in2 + Integer.toString(login.user_ID) + "@f" + Integer.toString(f_id) + ".com";
            System.out.println(email);
            ph = phone_text.getText();
            addr = addr_text.getText();
            
            sal = (Integer.parseInt(sal_text.getText())) * 1000;
            date = date_text.getText();
            bdate = bdate_text.getText();
            int old_e_id=Integer.parseInt(e_id_text.getText());
            String old_post=post;
            Class.forName("java.sql.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "table");
            Statement st= conn.createStatement();
            Statement st1= conn.createStatement();

            String query= "update employee set f_id= " + f_id + ",p_id=" + p_id + ",e_name='" + name + "', phone='" + ph + "',email_id='" + email + "',address='" + addr + "',post='" + post + "',salary=" + sal + ",join_date='" + date + "',birth_date='" + bdate + "' where e_id="+old_e_id+";";
            String query1 = "insert into login_employee values(" + (login.user_ID) + ",'" + bdate + "');"; //??
             
            st.executeUpdate(query);
            st1.executeUpdate(query1);
            
            if(old_post.equalsIgnoreCase("Manager"))
            {
           
                
                
                String man_id = new String();
                String man_pass = new String();
                
                man_pass = f_id_text.getText() + "%" + p_id_text.getText();
                Statement st2= conn.createStatement();
                
                String query2 = "update login_manager set pass='" + man_pass  + "' where username='+"+name+"';";//??
                st2.executeUpdate(query2);
                st2.close();
            } 
            
            
            
            st.close();
            st1.close();
            conn.close();
            JOptionPane.showMessageDialog(this, "Updated " + name);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error in updation");
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_update_buttonActionPerformed

    private void f_id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_id_textActionPerformed
        if(!f_id_text.getText().isEmpty())
        {
            try{
                Class.forName("java.sql.Driver");
            
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "table");
                Statement st= conn.createStatement();
                int f = Integer.parseInt(f_id_text.getText());
                String query4 = "select f_id, p_id from makes where f_id = " + f + ";";
                ResultSet rs = st.executeQuery(query4);
                while(rs.next())
                {
                    int fimp = rs.getInt("f_id");
                    if(fimp == f)
                    p_id_text.setText(Integer.toString(rs.getInt("p_id")));
                }
                rs.close();
                st.close();
                conn.close();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        else
            p_id_text.setText(null);



        // TODO add your handling code here:
    }//GEN-LAST:event_f_id_textActionPerformed

   
  
  
    
    private void sal_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sal_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sal_textActionPerformed

    private void pa_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pa_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pa_textActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new Owner_update().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void f_id_text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_id_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_id_text1ActionPerformed

    private void todayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayActionPerformed
        if(today.isSelected())
        {
            Date date = Calendar.getInstance().getTime();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date_text.setText(sdf.format(date));

            date_text.setEditable(false);
            //date = "current_date()";

        }
        else if(today.isSelected()!=true)
        {
            date_text.setEditable(true);

        }

        System.out.println(date);
        // TODO add your handling code here:
    }//GEN-LAST:event_todayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try
        {

            Class.forName("java.sql.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "table");
            Statement st= conn.createStatement();

            String query= "select * from employee where e_id = " + e_id_text.getText() + ";";
            ResultSet rs = st.executeQuery(query);

            while(rs.next())                                                                         //going to each row
            {

                String d2=rs.getString("e_name");
                System.out.println(d2);
                name_text.setText(d2);
                String d3=rs.getString("phone");
                phone_text.setText(d3);
                String d5=rs.getString("address");
                addr_text.setText(d5);
                String d6=Integer.toString(rs.getInt("f_id"));
                f_id_text.setText(d6);
                String d7=Integer.toString(rs.getInt("p_id"));
                p_id_text.setText(d7);
                String d8=rs.getString("post");
                post_text.setText(d8);
                String d9=rs.getString("salary");
                sal_text.setText(d9);
                String d10=rs.getDate("join_date").toString();
                date_text.setText(d10);
                String d11=rs.getDate("birth_date").toString();
                bdate_text.setText(d11);
                

            }

            st.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void e_id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_id_textActionPerformed
        // TODO add your handling code here:
                
      
        
    }//GEN-LAST:event_e_id_textActionPerformed

    private void post_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_post_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_post_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addr_label;
    private javax.swing.JPanel addr_panel;
    private javax.swing.JTextField addr_text;
    private javax.swing.JLabel bdate_label;
    private javax.swing.JPanel bdate_panel;
    private javax.swing.JTextField bdate_text;
    private javax.swing.JLabel date_label;
    private javax.swing.JPanel date_panel;
    private javax.swing.JTextField date_text;
    private javax.swing.JTextField e_id_text;
    private javax.swing.JLabel f_id_label;
    private javax.swing.JPanel f_id_panel;
    private javax.swing.JTextField f_id_text;
    private javax.swing.JTextField f_id_text1;
    private javax.swing.JPanel insert_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel name_label;
    private javax.swing.JPanel name_panel;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel p_id_label;
    private javax.swing.JPanel p_id_panel;
    private javax.swing.JTextField p_id_text;
    private javax.swing.JTextField pa_text;
    private javax.swing.JLabel phone_label;
    private javax.swing.JPanel phone_panel;
    private javax.swing.JTextField phone_text;
    private javax.swing.JTextField post_text;
    private javax.swing.JPanel purple_panel;
    private javax.swing.JLabel sal_label;
    private javax.swing.JTextField sal_text;
    private javax.swing.JPanel salary_panel;
    private javax.swing.JCheckBox today;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
