import java.awt.Color;
import javax.swing.JOptionPane;  
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class View_by_product extends javax.swing.JFrame {
    
    static int id1;
    static String name1;
    static float price1;
    static int units1;
    static String rawmat1;
    
            
    public void initialize()
    {
        name_text.setEditable(false);
        id_text.setEditable(false);
        
            price_text.setEditable(false);
            units_text.setEditable(false);
            rawmat_text.setEditable(false);
    }
    /**
     * Creates new form View_by_product
     */
    public View_by_product() {
        
        initComponents();
        initialize();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        error_dialog = new javax.swing.JDialog();
        error_panel1 = new javax.swing.JPanel();
        nothing_selected1 = new javax.swing.JLabel();
        okay_panel2 = new javax.swing.JPanel();
        okay_button2 = new javax.swing.JButton();
        owner_insert_buttongroup = new javax.swing.ButtonGroup();
        purple_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        name_panel = new javax.swing.JPanel();
        name = new javax.swing.JRadioButton();
        name_text = new javax.swing.JTextField();
        rawmat_panel = new javax.swing.JPanel();
        rawmat = new javax.swing.JRadioButton();
        rawmat_text = new javax.swing.JTextField();
        units_panel = new javax.swing.JPanel();
        units = new javax.swing.JRadioButton();
        units_text = new javax.swing.JTextField();
        id_panel = new javax.swing.JPanel();
        id = new javax.swing.JRadioButton();
        id_text = new javax.swing.JTextField();
        price_panel = new javax.swing.JPanel();
        price = new javax.swing.JRadioButton();
        price_text = new javax.swing.JTextField();
        choose_label = new javax.swing.JLabel();
        okay_panel = new javax.swing.JPanel();
        okay_button = new javax.swing.JButton();
        cancel_panel = new javax.swing.JPanel();
        cancel_button = new javax.swing.JButton();
        wholetable_panel = new javax.swing.JPanel();
        table = new javax.swing.JRadioButton();
        rawmat_panel1 = new javax.swing.JPanel();
        rawmat2 = new javax.swing.JRadioButton();

        error_dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        error_dialog.setBackground(new java.awt.Color(102, 0, 102));

        error_panel1.setBackground(new java.awt.Color(102, 0, 102));

        nothing_selected1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        nothing_selected1.setForeground(new java.awt.Color(255, 255, 255));
        nothing_selected1.setText("Nothing selected");

        okay_panel2.setBackground(new java.awt.Color(0, 0, 0));

        okay_button2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        okay_button2.setForeground(new java.awt.Color(255, 255, 255));
        okay_button2.setText("Okay");
        okay_button2.setContentAreaFilled(false);
        okay_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okay_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout okay_panel2Layout = new javax.swing.GroupLayout(okay_panel2);
        okay_panel2.setLayout(okay_panel2Layout);
        okay_panel2Layout.setHorizontalGroup(
            okay_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okay_button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        okay_panel2Layout.setVerticalGroup(
            okay_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okay_button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout error_panel1Layout = new javax.swing.GroupLayout(error_panel1);
        error_panel1.setLayout(error_panel1Layout);
        error_panel1Layout.setHorizontalGroup(
            error_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(error_panel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(nothing_selected1)
                .addContainerGap(88, Short.MAX_VALUE))
            .addComponent(okay_panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        error_panel1Layout.setVerticalGroup(
            error_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(error_panel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(nothing_selected1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(okay_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout error_dialogLayout = new javax.swing.GroupLayout(error_dialog.getContentPane());
        error_dialog.getContentPane().setLayout(error_dialogLayout);
        error_dialogLayout.setHorizontalGroup(
            error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(error_dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(error_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        error_dialogLayout.setVerticalGroup(
            error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(error_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(error_dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(error_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View by product");

        purple_panel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        name_panel.setBackground(new java.awt.Color(255, 255, 255));

        name.setBackground(new java.awt.Color(255, 255, 255));
        owner_insert_buttongroup.add(name);
        name.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        name.setText("Name:");
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        name_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        name_text.setBorder(null);
        name_text.setDisabledTextColor(new java.awt.Color(204, 51, 255));
        name_text.setSelectionColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout name_panelLayout = new javax.swing.GroupLayout(name_panel);
        name_panel.setLayout(name_panelLayout);
        name_panelLayout.setHorizontalGroup(
            name_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addGap(18, 18, 18)
                .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        name_panelLayout.setVerticalGroup(
            name_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(name_text, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        rawmat_panel.setBackground(new java.awt.Color(255, 255, 255));

        rawmat.setBackground(new java.awt.Color(255, 255, 255));
        owner_insert_buttongroup.add(rawmat);
        rawmat.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        rawmat.setText("Raw Material Used:");
        rawmat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rawmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawmatActionPerformed(evt);
            }
        });

        rawmat_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        rawmat_text.setBorder(null);
        rawmat_text.setDisabledTextColor(new java.awt.Color(204, 51, 255));
        rawmat_text.setSelectionColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout rawmat_panelLayout = new javax.swing.GroupLayout(rawmat_panel);
        rawmat_panel.setLayout(rawmat_panelLayout);
        rawmat_panelLayout.setHorizontalGroup(
            rawmat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rawmat_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rawmat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rawmat_text))
        );
        rawmat_panelLayout.setVerticalGroup(
            rawmat_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rawmat_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rawmat)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(rawmat_text, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        units_panel.setBackground(new java.awt.Color(255, 255, 255));

        units.setBackground(new java.awt.Color(255, 255, 255));
        owner_insert_buttongroup.add(units);
        units.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        units.setText("Units Manufactured/Day:");
        units.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        units.setMaximumSize(new java.awt.Dimension(164, 23));
        units.setMinimumSize(new java.awt.Dimension(164, 23));
        units.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitsActionPerformed(evt);
            }
        });

        units_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        units_text.setBorder(null);
        units_text.setDisabledTextColor(new java.awt.Color(204, 51, 255));
        units_text.setSelectionColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout units_panelLayout = new javax.swing.GroupLayout(units_panel);
        units_panel.setLayout(units_panelLayout);
        units_panelLayout.setHorizontalGroup(
            units_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(units_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(units, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(units_text))
        );
        units_panelLayout.setVerticalGroup(
            units_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(units_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(units, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(units_text, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        id_panel.setBackground(new java.awt.Color(255, 255, 255));

        id.setBackground(new java.awt.Color(255, 255, 255));
        owner_insert_buttongroup.add(id);
        id.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        id.setText("ID:");
        id.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        id_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        id_text.setBorder(null);
        id_text.setDisabledTextColor(new java.awt.Color(204, 51, 255));
        id_text.setSelectionColor(new java.awt.Color(0, 0, 0));
        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout id_panelLayout = new javax.swing.GroupLayout(id_panel);
        id_panel.setLayout(id_panelLayout);
        id_panelLayout.setHorizontalGroup(
            id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(id_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(id)
                .addGap(18, 18, 18)
                .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        id_panelLayout.setVerticalGroup(
            id_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(id_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(id)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(id_text, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        price_panel.setBackground(new java.awt.Color(255, 255, 255));

        price.setBackground(new java.awt.Color(255, 255, 255));
        owner_insert_buttongroup.add(price);
        price.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        price.setText("Unit Price:");
        price.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        price_text.setFont(new java.awt.Font("OCR A Extended", 0, 11)); // NOI18N
        price_text.setBorder(null);
        price_text.setDisabledTextColor(new java.awt.Color(204, 51, 255));
        price_text.setSelectionColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout price_panelLayout = new javax.swing.GroupLayout(price_panel);
        price_panel.setLayout(price_panelLayout);
        price_panelLayout.setHorizontalGroup(
            price_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(price_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(price_text, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        price_panelLayout.setVerticalGroup(
            price_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(price_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(price)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(price_text, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        choose_label.setBackground(new java.awt.Color(102, 0, 102));
        choose_label.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        choose_label.setForeground(new java.awt.Color(255, 255, 255));
        choose_label.setText("Choose attribute to filter by:");

        okay_panel.setBackground(new java.awt.Color(0, 0, 0));

        okay_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        okay_button.setForeground(new java.awt.Color(255, 255, 255));
        okay_button.setText("Okay");
        okay_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        okay_button.setContentAreaFilled(false);
        okay_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout okay_panelLayout = new javax.swing.GroupLayout(okay_panel);
        okay_panel.setLayout(okay_panelLayout);
        okay_panelLayout.setHorizontalGroup(
            okay_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okay_panelLayout.createSequentialGroup()
                .addComponent(okay_button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        okay_panelLayout.setVerticalGroup(
            okay_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okay_button, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        cancel_panel.setBackground(new java.awt.Color(0, 0, 0));

        cancel_button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cancel_button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_button.setText("Cancel");
        cancel_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        cancel_button.setContentAreaFilled(false);
        cancel_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_button.setName("Insert (Owner)"); // NOI18N
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cancel_panelLayout = new javax.swing.GroupLayout(cancel_panel);
        cancel_panel.setLayout(cancel_panelLayout);
        cancel_panelLayout.setHorizontalGroup(
            cancel_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cancel_panelLayout.setVerticalGroup(
            cancel_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        wholetable_panel.setBackground(new java.awt.Color(255, 255, 255));

        table.setBackground(new java.awt.Color(255, 255, 255));
        owner_insert_buttongroup.add(table);
        table.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        table.setText("View whole table");
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wholetable_panelLayout = new javax.swing.GroupLayout(wholetable_panel);
        wholetable_panel.setLayout(wholetable_panelLayout);
        wholetable_panelLayout.setHorizontalGroup(
            wholetable_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholetable_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        wholetable_panelLayout.setVerticalGroup(
            wholetable_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholetable_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        rawmat_panel1.setBackground(new java.awt.Color(255, 255, 255));

        rawmat2.setBackground(new java.awt.Color(255, 255, 255));
        owner_insert_buttongroup.add(rawmat2);
        rawmat2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        rawmat2.setText("Products sold today");
        rawmat2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rawmat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawmat2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rawmat_panel1Layout = new javax.swing.GroupLayout(rawmat_panel1);
        rawmat_panel1.setLayout(rawmat_panel1Layout);
        rawmat_panel1Layout.setHorizontalGroup(
            rawmat_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rawmat_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rawmat2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rawmat_panel1Layout.setVerticalGroup(
            rawmat_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rawmat2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(okay_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cancel_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choose_label)
                    .addComponent(id_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(units_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rawmat_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wholetable_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rawmat_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(choose_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(id_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(name_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(price_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(units_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(rawmat_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rawmat_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(wholetable_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okay_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout purple_panelLayout = new javax.swing.GroupLayout(purple_panel);
        purple_panel.setLayout(purple_panelLayout);
        purple_panelLayout.setHorizontalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purple_panelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        purple_panelLayout.setVerticalGroup(
            purple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purple_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        name_text.setEditable(true);
        name_text.setText("Enter a value");
        name_text.addMouseListener(new MouseAdapter(){
           
            public void mouseClicked(MouseEvent e){
                name_text.setText(null);
            }
        });
        id_text.setEditable(false);
         id_text.setText(null);
            price_text.setEditable(false);
            price_text.setText(null);
            units_text.setEditable(false);
            units_text.setText(null);
            rawmat_text.setEditable(false);
            rawmat_text.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
            
        id_text.setEditable(true);
       
        id_text.setText("Enter a value");
        id_text.addMouseListener(new MouseAdapter(){
           
            public void mouseClicked(MouseEvent e){
                id_text.setText(null);
            }
        });
        
        name_text.setEditable(false);
        name_text.setText(null);
            price_text.setEditable(false);
            price_text.setText(null);
            units_text.setEditable(false);
            units_text.setText(null);
            rawmat_text.setEditable(false);
            rawmat_text.setText(null);
// TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void okay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_buttonActionPerformed

        if(id.isSelected())
        {
            try{
            id1 = Integer.parseInt(id_text.getText());
            }
            catch(Exception e)
            {
                
            }
            this.dispose();
            new View_by_product_id().setVisible(true);
        }
        else if(name.isSelected())
        {
            
            name1 = name_text.getText();
            this.dispose();
            new View_by_product_name().setVisible(true);
        }
        else if(price.isSelected())
        {
            try{
            price1 = Float.parseFloat(price_text.getText());
            }
            catch(Exception e)
            {
                
            }
            this.dispose();
            new View_by_product_price().setVisible(true);
        }
        else if(units.isSelected())
        {
           try{
            units1 = Integer.parseInt(units_text.getText());
           }
           catch(Exception e)
            {
                
            }
            this.dispose();
            new View_by_product_units().setVisible(true);
        }
        else if(rawmat.isSelected())
        {
            
            rawmat1 = rawmat_text.getText();
            this.dispose();
            new View_by_product_rawmat().setVisible(true);
        }
        else if(rawmat2.isSelected())
        {
            
            
            this.dispose();
            new View_by_product_date().setVisible(true);
        }
        else if(table.isSelected())
        {
            this.dispose();
            new View_product_table().setVisible(true);
            
        }

        else
        {
            JOptionPane.showMessageDialog(error_dialog,"Nothing entered");
            //error_panel.setVisible(true);
        }

        //new login().user_ID++;//THIS IS NOT SUPPOSED TO BE HERE. PUT THIS IN ANOTHER .JAVA FILE WHERE YOU'LL INSERT VALUES FOR EMPLOYEES.

        //System.out.println(login.user_ID);
        //System.out.println(login.f_id);
        //System.out.println(login.s_id);

        // TODO add your handling code here:
    }//GEN-LAST:event_okay_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed

        this.dispose();                                                      //going to a new frame. right click on project name under projects tab, new->jframe form.
        new Owner_view().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void okay_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okay_button2ActionPerformed

    private void unitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitsActionPerformed
        
        units_text.setEditable(true);
        units_text.setText("Enter a value");
        units_text.addMouseListener(new MouseAdapter(){
           
            public void mouseClicked(MouseEvent e){
                units_text.setText(null);
            }
        });
         name_text.setEditable(false);
         name_text.setText(null);
            price_text.setEditable(false);
            price_text.setText(null);
            id_text.setEditable(false);
            id_text.setText(null);
            rawmat_text.setEditable(false);
            rawmat_text.setText(null);
// TODO add your handling code here:
    }//GEN-LAST:event_unitsActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        price_text.setEditable(true);
        price_text.setText("Enter a value");
        price_text.addMouseListener(new MouseAdapter(){
           
            public void mouseClicked(MouseEvent e){
                price_text.setText(null);
            }
        });
        name_text.setEditable(false);
        name_text.setText(null);
            id_text.setEditable(false);
            id_text.setText(null);
            units_text.setEditable(false);
            units_text.setText(null);
            rawmat_text.setEditable(false);
            rawmat_text.setText(null);
// TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void rawmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawmatActionPerformed
        rawmat_text.setEditable(true);
        rawmat_text.setText("Enter a value");
        rawmat_text.addMouseListener(new MouseAdapter(){
           
            public void mouseClicked(MouseEvent e){
                rawmat_text.setText(null);
            }
        });
        name_text.setEditable(false);
        name_text.setText(null);
            price_text.setEditable(false);
            price_text.setText(null);
            units_text.setEditable(false);
            units_text.setText(null);
            id_text.setEditable(false);
            id_text.setText(null);
// TODO add your handling code here:
    }//GEN-LAST:event_rawmatActionPerformed

    private void tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableActionPerformed
    name_text.setEditable(false);
        name_text.setText(null);
            price_text.setEditable(false);
            price_text.setText(null);
            units_text.setEditable(false);
            units_text.setText(null);
            id_text.setEditable(false);
            id_text.setText(null);
            rawmat_text.setEditable(false);
            rawmat_text.setText(null);
// TODO add your handling code here:
    }//GEN-LAST:event_tableActionPerformed

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textActionPerformed

    private void rawmat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawmat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rawmat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_by_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_by_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_by_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_by_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_by_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JPanel cancel_panel;
    private javax.swing.JLabel choose_label;
    private javax.swing.JDialog error_dialog;
    private javax.swing.JPanel error_panel1;
    private javax.swing.JRadioButton id;
    private javax.swing.JPanel id_panel;
    private javax.swing.JTextField id_text;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton name;
    private javax.swing.JPanel name_panel;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel nothing_selected1;
    private javax.swing.JButton okay_button;
    private javax.swing.JButton okay_button2;
    private javax.swing.JPanel okay_panel;
    private javax.swing.JPanel okay_panel2;
    private javax.swing.ButtonGroup owner_insert_buttongroup;
    private javax.swing.JRadioButton price;
    private javax.swing.JPanel price_panel;
    private javax.swing.JTextField price_text;
    private javax.swing.JPanel purple_panel;
    private javax.swing.JRadioButton rawmat;
    private javax.swing.JRadioButton rawmat2;
    private javax.swing.JPanel rawmat_panel;
    private javax.swing.JPanel rawmat_panel1;
    private javax.swing.JTextField rawmat_text;
    private javax.swing.JRadioButton table;
    private javax.swing.JRadioButton units;
    private javax.swing.JPanel units_panel;
    private javax.swing.JTextField units_text;
    private javax.swing.JPanel wholetable_panel;
    // End of variables declaration//GEN-END:variables
}
